sets.exported={
    main={ name="Midnights", augments={'Pet: Attack+25','Pet: Accuracy+25','Pet: Damage taken -3%',}},
    range="Animator P +1",
    ammo="Automat. Oil +3",
    head="Tali'ah Turban +1",
    body={ name="Pitre Tobe +1", augments={'Enhances "Overdrive" effect',}},
    hands={ name="Herculean Gloves", augments={'Pet: "Store TP"+10','Pet: DEX+5','Pet: "Mag.Atk.Bns."+8',}},
    legs={ name="Herculean Trousers", augments={'Pet: "Mag.Atk.Bns."+16','Pet: "Store TP"+11',}},
    feet={ name="Herculean Boots", augments={'Pet: Mag. Acc.+24','Pet: "Store TP"+10','Pet: AGI+5','Pet: "Mag.Atk.Bns."+13',}},
    neck="Shulmanu Collar",
    waist="Klouskap Sash",
    left_ear="Rimeice Earring",
    right_ear="Handler's Earring +1",
    left_ring="Varar Ring",
    right_ring="Overbearing Ring",
    back={ name="Visucius's Mantle", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20','Eva.+8 /Mag. Eva.+8','Pet: Attack+8 Pet: Rng.Atk.+8','Pet: "Regen"+10','Pet: Damage taken -5%',}},
}