sets.exported={
    main={ name="Midnights", augments={'Pet: Attack+25','Pet: Accuracy+25','Pet: Damage taken -3%',}},
    range="Animator P +1",
    ammo="Automat. Oil +3",
    head="Tali'ah Turban +1",
    body={ name="Taeon Tabard", augments={'Pet: Mag. Evasion+20','Pet: "Regen"+3','Pet: Damage taken -3%',}},
    hands="Heyoka Mittens",
    legs="Heyoka Subligar",
    feet="Tali'ah Crackows +1",
    neck="Bfn. Collar +1",
    waist="Klouskap Sash",
    left_ear="Handler's Earring",
    right_ear="Handler's Earring +1",
    left_ring="Warp Ring",
    right_ring="Overbearing Ring",
    back={ name="Visucius's Mantle", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20','Pet: "Regen"+10','Pet: Damage taken -5%',}},
}