sets.exported={
    main={ name="Ohtas", augments={'Accuracy+70','Pet: Accuracy+70','Pet: Haste+10%',}},
    range="Animator P +1",
    ammo="Automat. Oil +3",
    head="Karagoz Capello +1",
    body={ name="Pitre Tobe +1", augments={'Enhances "Overdrive" effect',}},
    hands="Karagoz Guanti +1",
    legs="Heyoka Subligar",
    feet="Tali'ah Crackows +1",
    neck="Shulmanu Collar",
    waist="Isa Belt",
    left_ear="Handler's Earring",
    right_ear="Handler's Earring +1",
    left_ring="Varar Ring",
    right_ring="Overbearing Ring",
    back={ name="Visucius's Mantle", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20','Pet: "Regen"+10','Pet: Damage taken -5%',}},
}